{{- if .Values.autoscaling.enabled }}
{{- if and .Values.monitoring.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name | trunc 57 }}-hpa
  labels:
    {{- include "nginx-fpm.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: 1
  maxReplicas: {{ .Values.replicaCount }}
  metrics:
    - type: Pods
      pods:
        metric:
          name: php_fpm_active_processes
        target:
          type: average
          value: {{ mul .Values.runtime.fpm.max_workers 0.8 }}
{{- end }}
{{- end }}
