{{- if and .Values.autoscaling.enabled (gt (.Values.replicaCount | int) 2) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name | trunc 57 }}-hpa
  labels:
    {{- include "nginx-fpm.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: 2
  maxReplicas: {{ .Values.replicaCount }}
  metrics:
    - type: Pods
      pods:
        metric:
          name: phpfpm_total_processes
        target:
          type: AverageValue
          averageValue: {{ ceil (mulf (.Values.runtime.fpm.max_workers | float64) 0.8) | int64 | quote }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
{{- end }}
