{{- if and .Values.monitoring.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name | trunc 57 }}-monitor
  namespace: {{ .Values.monitoring.prometheus.namespace | default .Release.Namespace }}
  labels:
    {{- if .Values.monitoring.prometheus.release }}
    release: {{ .Values.monitoring.prometheus.release }}
    {{- end }}
    {{- include "nginx-fpm.labels" . | nindent 4 }}
spec:
  {{- if .Values.monitoring.prometheus.namespace }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nginx-fpm.selectorLabels" . | nindent 6 }}
  endpoints:
    - path: /metrics
      targetPort: fpm-exporter
      {{- with (first .Values.ingress.hosts) }}
      metricRelabelings:
      - separator: ;
        regex: (.*)
        targetLabel: domain
        replacement: {{ .host }}
        action: replace
      {{- end }}
    - path: /metrics
      targetPort: nginx-exporter
      {{- with (first .Values.ingress.hosts) }}
      metricRelabelings:
      - separator: ;
        regex: (.*)
        targetLabel: domain
        replacement: {{ .host }}
        action: replace
      {{- end }}
    {{- if .Values.monitoring.opcache.enabled }}
    - path: {{ .Values.monitoring.opcache.uri_path }}
      targetPort: http
      {{- with (first .Values.ingress.hosts) }}
      metricRelabelings:
      - separator: ;
        regex: (.*)
        targetLabel: domain
        replacement: {{ .host }}
        action: replace
      {{- end }}
    {{- end }}
{{- end }}