{{- if .Values.verticalscaling.enabled }}
{{- if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1/VerticalPodAutoscaler" }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name | trunc 57 }}-vpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-fpm.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Release.Name }}
  updatePolicy:
    updateMode: {{ .Values.verticalscaling.updatePolicy.updateMode }}
  resourcePolicy:
    containerPolicies:
      {{- toYaml .Values.verticalscaling.containerPolicies | nindent 6 }}
{{- end }}
{{- end }}