# permissions for end users to view phpfpms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: phpfpm-viewer-role
rules:
- apiGroups:
  - runtime.cuppett.dev
  resources:
  - phpfpms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - runtime.cuppett.dev
  resources:
  - phpfpms/status
  verbs:
  - get
