{
 "title": "NGINX",
 "description": "Official dashboard for NGINX Prometheus exporter",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "domain", "query": { "query": "label_values(nginx_up, domain)" } },
   {
    "name": "pod",
    "query": {
     "query": "nginx_up{domain=~\"$domain\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX Status for $pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{domain=~\"$domain\", pod=~\"$pod\"}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Processed connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{domain=~\"$domain\", pod=~\"$pod\"}[$__range])",
     "legendFormat": "{{pod}} accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{domain=~\"$domain\", pod=~\"$pod\"}[$__range])",
     "legendFormat": "{{pod}} handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{domain=~\"$domain\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} active"
    },
    {
     "expr": "nginx_connections_reading{domain=~\"$domain\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} reading"
    },
    {
     "expr": "nginx_connections_waiting{domain=~\"$domain\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} waiting"
    },
    {
     "expr": "nginx_connections_writing{domain=~\"$domain\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} writing"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{pod=~\"$pod\"}[$__range])",
     "legendFormat": "{{instance}} total requests"
    }
   ]
  }
 ]
}