{
 "title": "OPcache",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "domain",
    "query": {
     "query": "label_values(php_opcache_enabled_boolean, domain)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "php_opcache_enabled_boolean{domain=~\"$domain\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hit Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(php_opcache_statistics_hit_ratio{domain=\"$domain\", pod=~\"$pod\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "php_opcache_memory_used_bytes{domain=\"$domain\", pod=~\"$pod\"} / (1024^2)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "php_opcache_statistics_hit_ratio{domain=\"$domain\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(php_opcache_memory_free_bytes{domain=\"$domain\", pod=~\"$pod\"})",
     "legendFormat": "Free Memory"
    },
    {
     "expr": "sum(php_opcache_memory_used_bytes{domain=\"$domain\", pod=~\"$pod\"})",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(php_opcache_memory_wasted_bytes{domain=\"$domain\", pod=~\"$pod\"})",
     "legendFormat": "Wasted"
    }
   ]
  },
  {
   "title": "Strings Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 3, "y": 10 },
   "targets": [
    {
     "expr": "php_opcache_strings_memory_used_bytes{domain=\"$domain\", pod=~\"$pod\"} / (1024^2)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Strings Stored",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "expr": "php_opcache_strings_count{domain=\"$domain\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Strings Memory Usage",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(php_opcache_strings_memory_free_bytes{domain=\"$domain\", pod=~\"$pod\"})",
     "legendFormat": "Free Memory"
    },
    {
     "expr": "sum(php_opcache_strings_memory_used_bytes{domain=\"$domain\", pod=~\"$pod\"})",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Cached Keys",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 3, "y": 20 },
   "targets": [
    {
     "expr": "php_opcache_statistics_cached_keys_count{domain=\"$domain\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cached Scripts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 20 },
   "targets": [
    {
     "expr": "php_opcache_statistics_cached_scripts_count{domain=\"$domain\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}