apiVersion: runtime.cuppett.dev/v1alpha1
kind: PhpFpm
metadata:
  name: phpfpm-sample
spec:
  # Default values copied from <project_dir>/helm-charts/nginx-fpm/values.yaml
  affinity: {}
  autoscaling:
    enabled: false
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  env:
    fpm:
    - name: PHP_UPLOAD_MAX_FILESIZE
      value: 64M
    nginx: []
  fullnameOverride: ""
  image:
    fpm:
      name: fedora-s2i-php
      repository: quay.io/cuppett
      sha: ""
      tag: "36-fpm"
    nginx:
      name: fedora-s2i-php
      repository: quay.io/cuppett
      sha: ""
      tag: "36-nginx"
    pullPolicy: Always
  imagePullSecrets: []
  ingress:
    annotations: {}
    enabled: false
    hosts: []
    tls: []
  monitoring:
    enabled: true
    prometheus:
      namespace: ""
      release: ""
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  replicaCount: 1
  resources:
    fpm: {}
    nginx: {}
  runtime:
    max_body: 64M
  securityContext: {}
  service:
    port: 8080
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  tolerations: []
  verticalscaling:
    containerPolicies: []
    enabled: false
    updatePolicy:
      updateMode: Auto
  volumeMounts: []
  volumes: []


